language: cpp


compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  include:
    - env: BUILD_TYPE=COMPILE
    - env: BUILD_TYPE=TEST
    - env: BUILD_TYPE=BENCH
  allow_failures:
    - os: osx

script:
  - if [ "$BUILD_TYPE" = "COMPILE" ]; then cmake .; fi
  - if [ "$BUILD_TYPE" = "COMPILE" ]; then cmake . -DTEST=TRUE; fi
  - if [ "$BUILD_TYPE" = "COMPILE" ]; then cmake . -DBENCHMARK=TRUE; fi
  - make
