language: cpp


compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=COMPILE BUILD_TYPE=RELEASE
    - env: BUILD_OPTIONS=TEST BUILD_TYPE=RELEASE
    - env: BUILD_OPTIONS=COMPILE BUILD_TYPE=DEBUG
    - env: BUILD_OPTIONS=TEST BUILD_TYPE=DEBUG
      allow_failures:
    - os: osx


script:
  - if [ "$BUILD_OPTIONS" = "COMPILE" ]; then if [ "$BUILD_TYPE" = "RELEASE" ]; then cmake . -DCMAKE_BUILD_TYPE=Release; else cmake. -DCMAKE_BUILD_TYPE=Debug; fi; fi
  - if [ "$BUILD_OPTIONS" = "TEST" ]; then if [ "$BUILD_TYPE" = "RELEASE" ]; then cmake . -DCMAKE_BUILD_TYPE=Release -DTEST=TRUE; else cmake . -DCMAKE_BUILD_TYPE=Debug -DTEST=TRUE; fi; fi 
  - make
