sudo: required
language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

stages:
  - compile
  - test
 - benchmark

script:
  - cmake .
  - make

jobs:
  include:
    - stage: compile
      script:
        - cmake . -DTEST=true
        - make
