language: cpp


compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=COMPILE
    - env: BUILD_OPTIONS=TEST
    - env: BUILD_OPTIONS=BENCHMARK
  allow_failures:
    - env: BUILD_OPTIONS=BENCHMARK
    - os: osx
      sudo: require

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake; brew upgrade cmake; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; sudo pip install codecov; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90; fi

script: 
  - if [ -z "$BUILD_OPTION" ]; then cmake . -DCMAKE_BUILD_TYPE="$BUILD_TYPE"; fi
  - if [ "$BUILD_OPTIONS" = "COMPILE" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug; fi
  - if [ "$BUILD_OPTIONS" = "TEST" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DTEST=TRUE; fi
  - if [ "$BUILD_OPTIONS" = "BENCHMARK" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DTEST=TRUE -DBENCHMARK=TRUE; fi
  - make
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ./run_gcov.sh; fi 
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then codecov; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
