language: cpp


compiler:
  - gcc

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_OPTIONS=COMPILE BUILD_TYPE=DEBUG

    - os: linux
      compiler: gcc
      env: BUILD_OPTIONS=TEST BUILD_TYPE=DEBUG

    - os: linux
      compiler: gcc
      env: BUILD_OPTIONS=BENCMARK BUILD_TYPE=DEBUG
      
    - os: linux
      compiler: clang
      env: BUILD_OPTIONS=COMPILE BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang
      env: BUILD_OPTIONS=TEST BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang
      env: BUILD_OPTIONS=BENCMARK BUILD_TYPE=DEBUG

    # Release Builds
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=RELEASE
    
    - os: linux
      compiler: clang
      env: BUILD_TYPE=RELEASE

    # OSX Builds
    - os: osx
      env: BUILD_OPTIONS=COMPILE BUILD_TYPE=DEBUG

    - os: osx
      env: BUILD_OPTIONS=TEST BUILD_TYPE=DEBUG

    - os: osx
      env: BUILD_OPTIONS=BENCHMARK BUILD_TYPE=DEBUG

  allow_failures:
    - os: osx
    - compiler: clang
    - env: BUILD_OPTIONS=BENCHMARK

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake; brew upgrade cmake gcc; brew install gcovr --overwrite; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -; sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" ; sudo apt-get update -qq; sudo pip install codecov; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install g++-8 -y; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /user/bin/clang++-3.8 100; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /user/bin/clang++-6.0 1000; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /user/bin/clang++-3.8 100; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang++ clang /user/bin/clang-3.8 100; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang clang /user/bin/clang-3.8 100; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang clang /user/bin/clang-6.0 1000; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --config clang; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --config clang++; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi

script: 
  - if [ -z "$BUILD_OPTION" ]; then cmake . -DCMAKE_BUILD_TYPE="$BUILD_TYPE"; fi
  - if [ "$BUILD_OPTIONS" = "COMPILE" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug; fi
  - if [ "$BUILD_OPTIONS" = "TEST" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DTEST=TRUE; fi
  - if [ "$BUILD_OPTIONS" = "BENCHMARK" ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DTEST=TRUE -DBENCHMARK=TRUE; fi
  - make
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$BUILD_OPTIONS" = "TEST" ]; then
        find ./CMakeFiles -name "*.gcno" -exec mv -t . {} \;
        find bin/tests/ -type f -exec {} \;
        find ./CMakeFiles -name "*.gcda"  -exec mv -t . {} \;
        ./run_gcov.sh;
        fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then bash <(curl -s https://codecov.io/bash) -t 42a329d2-3928-468b-80d4-6af2e4254968; fi
  
